### ISSUE TITLE
R&D substituting Nancy for Carter

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#141]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Subtask of #104 

### System Configuration

- CDP4 Web Services version:
  - [ ] CDP4Common:  
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

**Comment by samatrhea** [comment]
being handled in https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues/104
