### ISSUE TITLE
Element Definitions browsers - copy element definition between 2 models not possible

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-WebServices-Community-Edition#195]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

in testing COMET v8.0.0, encountered problem with copying element definition between 2 models. Checked on 2 servers, for both giving problems:
* DEV server (drag and drop from COMET launch test 202103 to Types Testing mdoel
* training server (drag and drop from Demo IEDD model to Temporary Exchange model

TBC if this is a real problem or related to servers not being up to date

error message: 
The CDP4 Services replied with code Forbidden: Forbidden: "exception:Only Element-Definition may be copied"

### Steps to Reproduce

open 2 models, with element definitions browsers.

### System Configuration

- CDP4 Web Services version:
  - [ ] CDP4Common:  
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

**Comment by lxatrhea** [comment]
@MartinFijneman  Could you provide more info? Was it caused by the fact that the user wasn't allowed to write the ElementDefinition based on his participant settings?

**Comment by lxatrhea** [comment]
@MartinFijneman: What to do with this?

**Comment by lxatrhea** [comment]
same as https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues/184
