### ISSUE TITLE
SetScale Operation throws exception during change persistance

### ISSUE THREAD

**Issue by stepjah** [RHEAGROUP/COMET-WebServices-Community-Edition#198]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-BatchEditor
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-BatchEditor-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-BatchEditor-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Operation SetScale creates an exception when trying to persist changes (e.g. change m -> mm for a certain category and parameter list) after the dry run runs without error.

### Steps to Reproduce
**Use the following command line:**
-s SERVER -u USER -p PASS -m MODEL --action SetScale --scale mm --parameters dim_x,dim_y,dim_z --categories COMP

**Resulting Error Message (after list of expected changes):**
`Persisting (34) changes in progress: <=2021-03-19 16:22:06.7302|ERROR|CDP4ServicesDal.CdpServicesDal|The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:Object reference not set to an instance of an object"
System.Exception: The inline update operation failed
 ---> CDP4Dal.Exceptions.DalWriteException: The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:Object reference not set to an instance of an object"
   at CDP4ServicesDal.CdpServicesDal.Write(OperationContainer operationContainer, IEnumerable`1 files)
   at CDP4Dal.Session.Write(OperationContainer operationContainer)
   at CDPBatchEditor.Extensions.DalSessionExtensions.Write(ISession session, IEnumerable`1 transactions) in C:\Projects\CDP4\CDP4-BatchEditor-Community-Edition\CDPBatchEditor\Extensions\DalSessionExtensions.cs:line 50'
  

### System Configuration

- [] COMET-BatchEditor version:1.1.0
- Environment (Operating system, version and so on): WIN10 64Bit
- .NET Framework version:
- Additional information:

**Comment by lxatrhea** [comment]
Related to #196
