### ISSUE TITLE
[Improve] Performance of ModelReferenceDataLibraryDao.GetSiteReferenceDataLibraryDependency function

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#229]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The `ModelReferenceDataLibraryDao.GetSiteReferenceDataLibraryDependency` function has a custom query defined to recursively get the rlds to form a chain of RDLs. This query is making use of the `SiteReferenceDataLibrary_View` and should be refactored to make use of the `SiteReferenceDataLibrary_Cache` for improved performance.

### Steps to Reproduce
NA

### System Configuration

- COMET Web Services version: 6.1.6

**Comment by lxatrhea** [comment]
@samatrhea This method is only called when a PersonPermission on SiteReferenceDataLibrary is set to READ_IF_PARTICIPANT.
According to AccessRightKindValidationService.IsPersonPermissionValid that could never happen. 
Only EngineeringModelSetup, IterationSetup, ModelReferenceDataLibrary and Participant can have a PersonPermission having a value of READ_IF_PARTICIPANT. So changing this method could be done, but in theory it cannot be executed.

**Comment by samatrhea** [comment]
@nlmave this makes the server more performant at login
