### ISSUE TITLE
An item with the same key has already been added Exception

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#262]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

Anh Toan reported an issue when transferring element definitions with parameters to the Hub, Stéphane reported the same problem. Could not reproduce yet. Seams to be related to perhaps a ParameterType. According to Anh Toan db dump, a DependentParameterTypeAssignment was causing this issue.

Contact @nathanatrhea for more info (SQL dump)

### System Configuration

- COMET Web Services version: 7.0.6
  - [x] CDP4Common:  8.1.0.0
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

**Comment by antoineatrhea** [comment]
It as been fixed with the PR #260, but it's not part of the latest release. The issue does not appear on the current development branch.

**Comment by alexatrhea** [comment]
Fixed in release 7.0.7
