### ISSUE TITLE
When an incomplete Person object is sent the server returns with an InternalServer error

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#264]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When the IME version 9.3.0.1 is used, the person dialog does not have validation implemented and and incomplete Person object can be sent. In case this is done, the server responds with an InternalServer error. The server shall never return that, so in case an invalid Person is sent, the server shall respond with an Invalid Operation or invalid POST message

This task is only done when also the integration test suite is updated veryfying that the proper error response is returned.

**Solution:**
An error for example is:
_The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:The \u0027Surname\u0027 property of a \u0027Person\u0027 is mandatory and cannot be empty or null."_

This should not be a 500 error.
Please check where it comes from and if there are more implementations like this.

### System Configuration

- COMET Web Services version:

**Comment by jan-at-rhea** [comment]
The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:The \u0027Surname\u0027 property of a \u0027Person\u0027 is mandatory and cannot be empty or null."

**Comment by jan-at-rhea** [comment]
![image](https://user-images.githubusercontent.com/112615243/198329517-86cf29c7-3e0e-48e7-b284-1300349461c7.png)
