### ISSUE TITLE
[FIX] Duplicate ParameterTypes on an ElementDefinition should not be created

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#269]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
@MartinFijneman  was able to create a duplicate parameter in an ElementDefinition from an end-user app. The server should prevent this from happening. Therefore the integration test suite needs to be extended to validate for each kind of ParameterType that a duplicate **cannot** be created. The following scenario's are requried:

  - in 2 separate transactions try to create a Parameter with the same ParameterType in the same ElementDefinition
  - in 1 transaction try to create 2 distinct Parameters that reference the same ParameterType in the same ElementDefinition

### System Configuration

- COMET Web Services version: 7.1.1

**Comment by MartinFijneman** [comment]
Steps performed by user with admin rights on server, and model administrator within model.

Description of steps that led to the double parameters:
in COMET IME: 
* in existing model, created new element definition "TestEQT" (with category)
* added parameter types absorptance, acceleration, accelerometer bias, accelerometer scale-factor, acquisition time,  action, active energy, active power

in clean workbook, using SIF plugin:
* connect to server, open model
* clicked generate button
*  in left grid: selected "TestEQT"
* in right grid: selected the parameter types above, as well as parameter type "xy"
* Note: in right grid: I changed applicable scale accelerotmeter scale-factor (rad/s) from default to 2nd possible scale ("ppm")
* generated sheet and saved

I don't remember now if I closed and reopened before going to next steps to submit values

in workbook, using SIF plugin:
* filled in values in the worksheet
* clicked import button
Note: at this point, all the parameter types appeared RED, indicating (suggesting) that these parameters were not yet existing
* clicked import

then in COMET IME:
* parameters appeared as double new parameters, see screenshot

![image](https://user-images.githubusercontent.com/35371313/218434855-fd57d49d-3645-44fe-838b-1859bff1b3dc.png)


Note: with further testing, was not able to reproduce this behaviour, the selected parameters in the import grid appeared correctly coloured YELLOW, indicating that they existed already, and needed to be updated in value only.

**Comment by samatrhea** [comment]
in cdao-dmap we have models that have the same, the issue is still there
