### ISSUE TITLE
[Add] RabbitMQ to send messages to any listener regarding updates to the data in a CDP4-COMET server

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#327]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Add RaabitMQ to notify a listener of changes to any data in the CDP4-COMET server
  - [ ] Add RabbitMQ to message listeners that a change has occured on any kind of Thing. An IThingMessageProducer service needs to be implemented that handles messaging and needs to be injected into the SiteDirectory and EngineeringModel Carter Module POST message handling.
  - [ ] add RabbitMQ connection setttings to appsettings.json and include an option to enable/disable messaging
  - [ ]  Add RabbitMQ to docker-compose for easy deployment
  - [ ] Add a messaging library to the CDP4-COMET-SDK that handles everything around messaging with RabbitMQ, such as the IThingMessageProducer and IThingMessageConsumer services and the defintiion of the message payloads etc.
  - [ ] any thing update event, corresponding to a transaction, can contain multiple things that are created updated and deleted. The following data shall be part of an update message. ChangedThings, TimeStamp, AcorID. It must be noted that the 10-25 protocol does not make it explicit that a Thing has been deleted. This is computed by computing the difference between state n and n+1 of the container Thing that contains the Thing that has been deleted

> NOTE: make sure that any calls to the queue are non-blocking and that the CDP4-COMET server is impacted as less as possible (we don't want this to slow us down)

I suggest to use the following naming conventions:
  - Exchange name: `cdp4cometexchange` (or cdp4-comet-exchange or cdp4_comet_exchange)
  - Queue name: `thingqueue` (or thing-queue, or thing_queue)
  - The `thingqueue` queue shall be bound to the `cdp4cometexchange`  exchange

### Steps to Reproduce
NA

### System Configuration

- COMET Web Services version: 8.0.0-RC21

**Comment by nathanatrhea** [comment]
As we might want one thing message to be delivered to any number of listeners. 

The issue we could come across by having only one thingqueue is that the message acknowledgement of the delivery of the message cannot be done. When publishing to one exchange/queue there can be only one client / per message in a round-robin fashion when the acknowledgement is set to auto. Unless there is no acknowledgement of the delivery then all the connected listeners will get the message over and over (as well as whenever listeners re-connect to the queue).

I suggest to use a broadcast type of message. with one dedicated exchange per "message type" and as many client as temporary thingqueue bound to the exchange. In short I suggest to use exchanges as "thingqueues" over queues

**Comment by samatrhea** [comment]
> As we might want one thing message to be delivered to any number of listeners.
> 
> The issue we could come across by having only one thingqueue is that the message acknowledgement of the delivery of the message cannot be done. When publishing to one exchange/queue there can be only one client / per message in a round-robin fashion when the acknowledgement is set to auto. Unless there is no acknowledgement of the delivery then all the connected listeners will get the message over and over (as well as whenever listeners re-connect to the queue).
> 
> I suggest to use a broadcast type of message. with one dedicated exchange per "message type" and as many client as temporary thingqueue bound to the exchange. In short I suggest to use exchanges as "thingqueues" over queues

understood, please proceed as suggested
