### ISSUE TITLE
Update of ValueArray with string.empty should not be allowed

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#332]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

It is allowed to update a ValueArray with string.empty. It will produce errors inside the model since the ValueArray required to have at least one value, which should not be null or empty.

### Steps to Reproduce

- In CDP4-COMET IME, update any value of a Parameter to set the entry as string.empty
- Click somewhere else to apply the change
- Refresh or reload
- Check that an error occurs on the Error tab that state that a ValueArray should requires 1 value
### System Configuration

- COMET Web Services version:8.0.0-RC23 
  - [ ] CDP4Common:  24.6.0
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

**Comment by antoineatrhea** [comment]
@samatrhea I think that one can be closed since it this handle in the DTOValidation (https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pull/337)

**Comment by samatrhea** [comment]
agreed
