### ISSUE TITLE
Performance issue for creating a new EngineeringModel based on an existing model

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#41]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When creating a model based on an existing model the process takes a long time due to which the transaction on PostgreSQL times-out.

### Steps to Reproduce
create a model based on an existing model

### System Configuration

- CDP4 Web Services version: 3.2.0

**Comment by naronatrhea** [comment]
is the LOFT big enough to reproduce this?

**Comment by samatrhea** [comment]
in private email from users this was communicated. I am currently trying to improve performance by creating a dump of a postgres schema and using find-n-replace in the data to update the unique identifiers in the new model.

**Comment by samatrhea** [comment]
When a server is setup (today also present in the template sql dunp) we have the following SQL statement:

```
ALTER ROLE cdp4 SET statement_timeout TO '30000';
```

This needs to be removed so that the role is not limited to a certain timeout and we can rely on settings of the connection or database itself

**Comment by antoineatrhea** [comment]
Closed with #323
