### ISSUE TITLE
As a user I want to visualize how a value of a parameter has changed over time

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#98]
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Related to: https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/243

We need to implement the functionality to also be able to put timestamps in the revisionTo and revisionFrom HTTP query parameters.
At the moment only integer values are allowed as valid values for those two HTTP query parameters.

**Comment by antoineatrhea** [comment]
@samatrhea It seams to be already done... Related issues are closed and this one has been moved to the _Done_ column. Can you confirm ?
